---
version: 2
registries:
  dockerhub: 
    type: docker-registry
    url: https://registry.hub.docker.com
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    replaces-base: false
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: "Europe/Oslo"
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: "Europe/Oslo"
    open-pull-requests-limit: 5
  - package-ecosystem: docker
    directory: "/"
    registries:
      - dockerhub
    schedule:
      interval: daily
      time: "09:00"
      timezone: "Europe/Oslo"
    open-pull-requests-limit: 5
  - package-ecosystem: docker
    directory: "/kubernetes-manifests/"
    registries:
      - dockerhub
    schedule:
      interval: daily
      time: "09:00"
      timezone: "Europe/Oslo"
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: "Europe/Oslo"
    open-pull-requests-limit: 5
