---
approval_rules:
  - description: A rule that requires status checks to be green
    if:
      has_successful_status:
        - "Linting / Commit linting"
        - "Linting / Golang linting"
    name: status checks
    options:
      allow_author: false
      allow_contributor: false
      invalidate_on_push: true

  - description: A rule that dont require approvals if signed by pre-approved signing-keys
    if:
      has_valid_signatures: true
      has_valid_signatures_by_keys:
        key_ids:
          - 4E0ED32BE590D451
          - 7115251C2B41A5EC
          - SHA256:43xMON8v36mP3nlDbcMbiByM/0W7vY2150k2yUOdMx0
    name: pre-approved signatures
    requires:
      count: 0

  - description: Rule to approve PR when label is patch, author is dependabot
    if:
      author_is_only_contributor: true
      has_author_in:
        users:
          - "dependabot[bot]"
      has_labels:
        - "dependencies"
        - "patch"
      has_valid_signatures: true
      has_valid_signatures_by_keys:
        key_ids:
          - B5690EEEBB952194
    name: dependabot-patch
    requires:
      count: 0

  - description: Rule to approve PR when label is minor, author is dependabot
    if:
      author_is_only_contributor: true
      has_author_in:
        users:
          - "dependabot[bot]"
      has_labels:
        - "dependencies"
        - "minor"
      has_valid_signatures: true
      has_valid_signatures_by_keys:
        key_ids:
          - B5690EEEBB952194
    name: dependabot-minor
    requires:
      count: 0

  - description: review when needed
    name: reviews
    options:
      request_review:
        enabled: true
        mode: teams
    requires:
      count: 1
      permissions:
        - "write"
      teams:
        - "Sea-Shell/seashell"

policy:
  approval:
    - status checks
    - and:
        - pre-approved signatures
        - or:
            - reviews
            - dependabot-patch
            - dependabot-minor
  disapproval:
    requires:
      teams:
        - "Sea-Shell/seashell"
