---
approval_rules:
  - description: A rule that requires status checks to be green
    if:
      has_successful_status:
        - "commit-lint / Commit linting"
        - "golang-lint / Golang linting"
    name: status checks
    options:
      allow_contributor: false
      invalidate_on_push: false
      request_review:
        enabled: true
        mode: teams

  - description: A rule that dont require approvals if from seashell
    if:
      author_is_only_contributor: true
      has_valid_signatures: true
      has_valid_signatures_by_keys:
        key_ids:
          - 4E0ED32BE590D451
      modified_lines:
        total: "< 200"
      only_has_contributors_in:
        teams:
          - "Sea-Shell/seashell"
    name: seashell-auto-approval
    options:
      allow_author: false
      allow_contributor: false
    requires:
      count: 0

  - description: Rule to approve PR when label is patch, author is dependabot
    if:
      author_is_only_contributor: true
      has_author_in:
        users:
          - "dependabot[bot]"
      has_labels:
        - "dependencies"
        - "patch"
      has_valid_signatures: true
      has_valid_signatures_by_keys:
        key_ids:
          - B5690EEEBB952194
    name: dependabot-patch
    requires:
      count: 0

  - description: Rule to approve PR when label is minor, author is dependabot
    if:
      author_is_only_contributor: true
      has_author_in:
        users:
          - "dependabot[bot]"
      has_labels:
        - "dependencies"
        - "minor"
      has_valid_signatures: true
      has_valid_signatures_by_keys:
        key_ids:
          - B5690EEEBB952194
    name: dependabot-minor
    requires:
      count: 0

policy:
  approval:
    - and:
        - status checks
        - or:
            - seashell-auto-approval
            - dependabot-patch
            - dependabot-minor
  disapproval:
    requires:
      teams:
        - "Sea-Shell/seashell"
