CREATE TABLE IF NOT EXISTS users (
    userId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT DEFAULT 0,
    userUsername TEXT NOT NULL,
    userPassword TEXT NOT NULL,
    userName TEXT,
    userEmail TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS gear (
    gearId INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT 0,
    gearTopCategoryId INTEGER NOT NULL,
    gearCategoryId INTEGER NOT NULL,
    gearManufactureId INTEGER NOT NULL,
    gearName TEXT NOT NULL,
    gearWeight INTEGER,
    gearHeight INTEGER,
    gearLength INTEGER,
    gearWidth INTEGER,
    gearStatus BOOLEAN,
    FOREIGN KEY (gearTopCategoryId) REFERENCES gear_top_category(topCategoryId),
    FOREIGN KEY (gearCategoryId) REFERENCES gear_category(categoryId),
    FOREIGN KEY (gearManufactureId) REFERENCES manufacture(manufactureId)
);
CREATE INDEX topCategory_index ON gear(gearTopCategoryId);
CREATE INDEX category_index ON gear(gearCategoryId);
CREATE INDEX manufacture_index ON gear(gearManufactureId);

CREATE TABLE IF NOT EXISTS manufacture (
    manufactureId INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT 0,
    manufactureName TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS gear_top_category (
    topCategoryId INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT 0,
    topCategoryName TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS gear_category (
    categoryId INTEGER PRIMARY KEY AUTOINCREMENT DEFAULT 0,
    categoryTopCategoryId INTEGER NOT NULL,
    categoryName TEXT NOT NULL,
    FOREIGN KEY (categoryTopCategoryId) REFERENCES gear_top_category(topCategoryId)
);

CREATE TABLE IF NOT EXISTS user_gear_registrations (
    gearId INTEGER NOT NULL,
    userId INTEGER NOT NULL,
    FOREIGN KEY (gearId) REFERENCES gear(gearId),
    FOREIGN KEY (userId) REFERENCES users(userId)
);

INSERT INTO users (userUsername, userPassword, userName, userEmail) VALUES 
    ("Bateau", "$2a$10$X2BAOJFWXxAudCm9ShaHvucsdv1.dz3pdbBPf6bJerWs7YJB7KV9", "Mats Bøe Bergmann", "mats.bergmann@gmail.com");

INSERT INTO gear_top_category (topCategoryName) VALUES 
    ("Footwear"),
    ("Clothing"),
    ("Backpacks"),
    ("Navigation and Safety"),
    ("Shelter"),
    ("Sleeping Gear"),
    ("Cooking"),
    ("Hiking Accessories"),
    ("Emergency and Communication"),
    ("Apparel Accessories");

INSERT INTO gear_category (categoryName, categoryTopCategoryId) VALUES 
    ("Hiking boots", 1),
    ("Trail shoes", 1),
    ("Hiking socks", 1),
    ("Gaiters", 1),
    ("Moisture-wicking base layers", 2),
    ("Moisture-wicking shirts", 2),
    ("Hiking pants", 2),
    ("shorts", 2),
    ("Insulation", 2),
    ("Rain jacket", 2),
    ("Rain pants", 2),
    ("Hat", 2),
    ("Sun hat", 2),
    ("Beanie", 2),
    ("Gloves", 2),
    ("Hiking backpack", 3),
    ("Daypack", 3),
    ("Hydration backpack", 3),
    ("Water bottle", 3),
    ("Maps", 4),
    ("Compass", 4),
    ("GPS", 4),
    ("Smartphone", 4),
    ("Whistle", 4),
    ("First aid kit", 4),
    ("Multi-tool", 4),
    ("knife", 4),
    ("Tent", 5),
    ("Footprint", 5),
    ("Tarp", 5),
    ("Emergency space blanket", 5),
    ("Bivy sack", 5),
    ("Ground tarp", 5),
    ("Sleeping bag", 6),
    ("Duvet", 6),
    ("Sleeping pad", 6),
    ("Air mattress", 6),
    ("Pillow", 6),
    ("Stove", 7),
    ("Fuel", 7),
    ("Cookware Pot", 7),
    ("Pan", 7),
    ("Utensils", 7),
    ("Lightweight food", 7),
    ("Water purification system", 7),
    ("Bear canister", 7),
    ("Trekking poles", 8),
    ("Sunglasses", 8),
    ("Sunscreen", 8),
    ("Insect repellent", 8),
    ("Headlamp", 8),
    ("Flashlight", 8),
    ("Batteries", 8),
    ("Camera", 8),
    ("Satellite communicator", 9),
    ("Personal Locator Beacon", 9),
    ("Two-way radios", 9),
    ("Bandana", 10),
    ("Buff", 10),
    ("Neck gaiter", 10),
    ("gloves", 10);


INSERT INTO manufacture (manufactureId, manufactureName) VALUES
    (1, "The North Face"),
    (2, "Patagonia"),
    (3, "Columbia Sportswear"),
    (4, "Arc'teryx"),
    (5, "Salomon"),
    (6, "Outdoor Research"),
    (7, "Marmot"),
    (8, "Black Diamond Equipment"),
    (9, "Osprey"),
    (10, "Gregory"),
    (11, "Deuter"),
    (12, "Kelty"),
    (13, "MSR (Mountain Safety Research)"),
    (14, "Petzl"),
    (15, "Merrell"),
    (16, "Keen"),
    (17, "Vasque"),
    (18, "La Sportiva"),
    (19, "Scarpa"),
    (20, "Mammut"),
    (21, "Hilleberg"),
    (22, "Big Agnes"),
    (23, "Therm-a-Rest"),
    (24, "REI Co-op"),
    (25, "Gossamer Gear"),
    (26, "Granite Gear"),
    (27, "Sea to Summit"),
    (28, "Rab"),
    (29, "Montane"),
    (30, "Fjällräven"),
    (31, "Hoka One One"),
    (32, "Oboz"),
    (33, "Altra"),
    (34, "Inov-8"),
    (35, "Lowa"),
    (36, "Exped"),
    (37, "Hyperlite Mountain Gear"),
    (38, "NEMO Equipment"),
    (39, "Western Mountaineering"),
    (40, "MontBell"),
    (41, "Garmont"),
    (42, "Salewa"),
    (43, "ORTOVOX"),
    (44, "Snow Peak"),
    (45, "Cotopaxi"),
    (46, "Klymit"),
    (47, "Blackyak"),
    (48, "Zamberlan"),
    (49, "Norrøna"),
    (50, "Devold"),
    (51, "Sweet Protection"),
    (52, "Lundhags"),
    (53, "Haglöfs"),
    (54, "Millet"),
    (55, "Vaude"),
    (56, "Wild Country"),
    (57, "Grivel"),
    (58, "CAMP"),
    (59, "Edelrid"),
    (60, "Sterling Rope"),
    (61, "BlueWater Ropes"),
    (62, "Five Ten"),
    (63, "Evolv"),
    (64, "Metolius Climbing"),
    (65, "Beal"),
    (66, "Maxim Ropes"),
    (67, "Trango"),
    (68, "Edelweiss"),
    (69, "Misty Mountain"),
    (70, "Camp USA"),
    (71, "Cassin"),
    (72, "DMM"),
    (73, "Houdini"),
    (74, "Didriksons"),
    (75, "Helly Hansen"),
    (76, "Bach"),
    (77, "Peak Performance"),
    (78, "Arctix"),
    (79, "Ulvang"),
    (80, "66°North"),
    (81, "Hestra"),
    (82, "Bula"),
    (83, "O'Neill"),
    (84, "Kari Traa"),
    (85, "Dale of Norway"),
    (86, "Icebreaker"),
    (87, "Trangia"),
    (88, "Bergans"),
    (89, "Crispi");