name: "Release build and push"

on:
  push:
    tags:
      - "v*"

env:
  IMAGE_REGISTRY: registry.hub.docker.com
  IMAGE_REPOSITORY: bateau
  IMAGE_NAME: gogear-api

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.0
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Get release version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Build and push
        id: build_push
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max,ignore-error=true
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
