name: Generate Swagger Docs

on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - "v*"

permissions:
  contents: read

jobs:
  generate-swagger-docs:
    name: Generate Swagger Docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v4.1.0

      - name: Setup GoLang
        uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.21'
          check-latest: true

      - name: Install swag cmd
        shell: bash
        run:
          go install github.com/swaggo/swag/cmd/swag@latest
          
      - name: Generate swagger docs
        shell: bash
        run: 
          swag init --generatedTime

      - name: Push updated swagger docs
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: "docs: update swagger definitions"
          file_pattern: 'docs/docs.go docs/swagger.yaml docs/swagger.json'
          skip_checkout: true
          skip_dirty_check: true
          skip_fetch: true