name: Generate Swagger Docs

on:
  push:
    branches-ignore:
      - main
      - dependabot/**
    tags-ignore:
      - "v*"

permissions:
  contents: read

jobs:
  generate-swagger-docs:
    name: Generate Swagger Docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v4.1.3
        with:
          fetch-depth: 2

      - name: Setup GoLang
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true

      - name: Install swag cmd
        shell: bash
        run:
          go install github.com/swaggo/swag/cmd/swag@latest
          
      - name: Generate swagger docs
        shell: bash
        run: 
          swag init --outputTypes json,yaml --output docs/

      - name: Get last commit message
        id: last-commit-message
        run: |
          echo "msg=$(git log -n 1 --pretty=format:%B)" >> $GITHUB_OUTPUT
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'docs/docs.go docs/swagger.json docs/swagger.yaml'
          commit_message: ${{ steps.last-commit-message.outputs.msg }}
          commit_options: '--amend --no-edit'
          push_options: '--force'
          skip_fetch: true